### ISSUE TITLE
目前需紧急开发这四个题目

### ISSUE THREAD

**Issue by psychelzh** [iquizoo/docs#27]
- [x] WM-速算大师（C2）变式 #29 #32 #39 
- [x] WM-蝴蝶照相机（新）（Automated Complex Span） #30 #37 
- [x] VSTM-雷达追踪（H5-V4）变式 #28 #33 
- [x] EM-物体位置记忆（H5-V4）变式 #31

**Comment by psychelzh** [comment]
Now it is kind of obsolete and inactive. And the works are actually completed in some other format.
